### ISSUE TITLE
Crash in MPPersistenceController

### ISSUE THREAD

**Issue by kballard** [mParticle/mparticle-apple-sdk#35]
We just updated from v6.9.0 to v6.10.0 and we have a brand new crash that looks like

```
Fatal Exception: NSInvalidArgumentException
-[MPStandaloneMessage sessionId]: unrecognized selector sent to instance 0x174c67bc0

0  CoreFoundation                 0x18c4fc1c0 __exceptionPreprocess
1  libobjc.A.dylib                0x18af3455c objc_exception_throw
2  CoreFoundation                 0x18c503278 __methodDescriptionForSelector
3  CoreFoundation                 0x18c500278 ___forwarding___
4  CoreFoundation                 0x18c3fa59c _CF_forwarding_prep_0
5  mParticle_Apple_SDK            0x100e52f38 __39-[MPPersistenceController saveMessage:]_block_invoke (MPPersistenceController.mm:2096)
6  libdispatch.dylib              0x18b3851c0 _dispatch_client_callout
7  libdispatch.dylib              0x18b392860 _dispatch_barrier_sync_f_invoke
8  mParticle_Apple_SDK            0x100e52df4 -[MPPersistenceController saveMessage:] (MPPersistenceController.mm:2119)
9  mParticle_Apple_SDK            0x100e313e0 -[MPBackendController handleApplicationWillTerminate:] (MPBackendController.mm:1344)
10 CoreFoundation                 0x18c49622c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
11 CoreFoundation                 0x18c495930 _CFXRegistrationPost
12 CoreFoundation                 0x18c4956ac ___CFXNotificationPost_block_invoke
13 CoreFoundation                 0x18c504b9c -[_CFXNotificationRegistrar find:object:observer:enumerator:]
14 CoreFoundation                 0x18c3d7bf4 _CFXNotificationPost
15 Foundation                     0x18cede6bc -[NSNotificationCenter postNotificationName:object:userInfo:]
16 UIKit                          0x1923d1478 -[UIApplication _terminateWithStatus:]
17 UIKit                          0x1925d3864 __102-[UIApplication _handleApplicationDeactivationWithScene:shouldForceExit:transitionContext:completion:]_block_invoke.2098
18 UIKit                          0x1925d7074 _runAfterCACommitDeferredBlocks
19 UIKit                          0x1925c8e28 _cleanUpAfterCAFlushAndRunDeferredBlocks
20 UIKit                          0x192337b80 _afterCACommitHandler
21 CoreFoundation                 0x18c4a97dc __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
22 CoreFoundation                 0x18c4a740c __CFRunLoopDoObservers
23 CoreFoundation                 0x18c4a789c __CFRunLoopRun
24 CoreFoundation                 0x18c3d6048 CFRunLoopRunSpecific
25 GraphicsServices               0x18de59198 GSEventRunModal
26 UIKit                          0x1923b0628 -[UIApplication _run]
27 UIKit                          0x1923ab360 UIApplicationMain
28 Postmates                      0x1000c8a10 main (main.m:38)
29 libdispatch.dylib              0x18b3b85b8 (Missing)
```

This occurs on both iOS 9 and iOS 10.

**Comment by kballard** [comment]
This crash occurs immediately after `UIApplicationDelegate. applicationWillTerminate(_:)` is invoked, though you can probably figure this out from the stack trace. I would assume this is caused by 1ba9234ec40bf91325f3172da3b7f40d2914d19e.

**Comment by kballard** [comment]
This appears to be affecting a non-trivial number of users.

**Comment by rshehata** [comment]
Hi Kevin,

Our Mobile Engineering team are on it and actively working through issue.

We'll reach out with more details and a resolution shortly.

In the meantime, please feel free to contact customer-success@mparticle.com for all issues.

**Comment by tanner-pm** [comment]
@rshehata Can you please take a look.

**Comment by rshehata** [comment]
@tanner-pm & @kballard 

Issue has been resolved and we've released an SDK update. Release details can be found on our Github here: https://github.com/mParticle/mparticle-apple-sdk/releases/tag/6.10.3

Please feel free to contact customer-success@mparticle.com with any further issues.

Thanks!

**Comment by hatebyte** [comment]
We are still seeing the issue with 6.10.3. At least a couple hundred times a day.

**Comment by dcirne** [comment]
Hi @hatebyte, we discovered a second scenario where the issue described could happen and released a fix for it in version 6.11.0 of the SDK. You can see the commit with the change here: https://github.com/mParticle/mparticle-apple-sdk/commit/7fa479aa5f7aa556078a5482a7f2fcc21cf8c8ad

**Comment by hatebyte** [comment]
Will do. thank you.
